Cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path("", views.cart_detail, name='detail'),
    path("add/<int:product_id>/",
         views.cart_add,
         name="add"
         ),
    path("remove/<int:product_id>/",
         views.cart_remove,
         name="remove"
         ),
]

Products/models.py
from django.db import models
from django.shortcuts import render
from wagtail.core.fields import RichTextField
from wagtail.core.models import Orderable, Page
from django import forms
from wagtail.snippets.models import register_snippet
from wagtail.contrib.routable_page.models import RoutablePageMixin, route
from taggit.models import TaggedItemBase, Tag as TaggitTag
from wagtail.admin.edit_handlers import (
    FieldPanel,
    InlinePanel,
    PageChooserPanel,
)
from modelcluster.tags import ClusterTaggableManager
from wagtail.images.edit_handlers import ImageChooserPanel

from modelcluster.fields import (
    ParentalKey,
    ParentalManyToManyField
)
class ProductIndexPage(RoutablePageMixin,Page):
    intro = RichTextField(blank=True)
    content_panels = Page.content_panels + [
        FieldPanel("intro"),
    ]
    subpage_types = [
        "Products.Product",
    ]
    max_count = 1


    def get_posts(self):
        return ProductIndexPage.objects.descendant_of(self).live()

    def get_context(self, request, *args, **kwargs):
        context = super().get_context(request)
        context["products"] = Product.objects.all()
        context['categories'] = ProductCategory.objects.all()
        context['i'] = 0
        print(context['products'])
        return context


    @route(r'^category/(?P<category>[-\w]+)/$')
    def post_by_category(self, request, category, *args, **kwargs):
        context = super().get_context(request)
        self.search_type = 'category'
        self.search_term = category
        context['categories'] = ProductCategory.objects.all()
        context["products"] = Product.objects.all().filter(Categories__slug = category)
        return render(request, 'Products/product_list.html',context )

    @route(r'^search/$')
    def post_search(self, request, *args, **kwargs):
        search_query = request.GET.get('q', None)
        context = super().get_context(request)
        context['categories'] = ProductCategory.objects.all()
        self.posts = self.get_posts()
        print(self.posts)
        if search_query:
            context['products'] = self.posts.filter(title__contains=search_query)
            self.search_term = search_query
            self.search_type = 'search'
        return render(request, 'Products/product_list.html',context )



class Product(Page):
    date = models.DateTimeField(blank=True, null=True)
    Description = models.TextField(blank = True)
    Price = models.DecimalField(max_digits=10, decimal_places=2)
    Available = models.BooleanField(default=True)
    TopFeatured = models.BooleanField(default=False)
    Categories=ParentalManyToManyField("Products.ProductCategory", blank=True)
    tags = ClusterTaggableManager(through ="Products.ProductTag", blank=True)
    sex = models.CharField(max_length =20,choices = (("1", 'Male'), ('2' , 'Female'), ('3', 'Unisex'), ('4', 'Kids')) , default = '1')
    subpage_types = []
    content_panels = Page.content_panels + [
        FieldPanel("Description", classname="full"),
        FieldPanel("Price"),
        FieldPanel("Available"),
        FieldPanel("TopFeatured"),
        FieldPanel('tags'),
        FieldPanel('sex'),
        FieldPanel('Categories', widget =forms.CheckboxSelectMultiple),
        InlinePanel('gallery_images', label="Gallery images"),
    ]


    @property
    def get_product_index_page(self):
        return self.get_parent().specific

    def get_context(self, request, *args, **kwargs):
        context = super().get_context(request)
        context["product_index_page"] = self.get_product_index_page
        context["products"] = Product.objects.all()
        return context


class ProductGalleryImage(Orderable):
    page = ParentalKey(Product, related_name='gallery_images')
    image = models.ForeignKey('wagtailimages.Image', on_delete=models.CASCADE, related_name='+')
    caption = models.CharField(blank=True, max_length=250)
    panels = [ImageChooserPanel('image'),FieldPanel('caption'),]

@register_snippet
class ProductCategory(models.Model):
    name= models.CharField(max_length=255)
    slug=models.SlugField(unique=True,max_length=80)
    Caterogy_Description = models.TextField(blank=True)
    image = models.ForeignKey(
        "wagtailimages.Image", on_delete=models.SET_NULL, null=True, related_name="+"
    )
    panels=[
        FieldPanel('Caterogy_Description'),
        FieldPanel('name'),
        FieldPanel('slug'),
        ImageChooserPanel('image')
    ]
    def __str__(self):
        return self.name

    def get_all_category(self):
        all_category=ProductCategory.Objects.all()
        return all_category
        
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural='Categories'

class ProductTag(TaggedItemBase):
    content_object=ParentalKey('Product',related_name='product_tag')

@register_snippet
class Tag(TaggitTag):
    class Meta:
        proxy=True

Products/views.py
from django.shortcuts import render

# Create your views here.

Products/templates/Products/product.html
{% extends "base.html" %} {% load static %} {% load wagtailimages_tags wagtailroutablepage_tags %} 
{% block content %}
<div style="height:15rem; " class="flex-column-reverse">
</div>
  <section class="mt-lg-5 ">
    <!-- section for detail part-->
    <div class="container">
      <div class="row">
        <div class=" col-lg-2">
          {% for item in page.gallery_images.all %}
          <div class=" border mr-4 d-flex justify-content-center mt-2">
            {% image item.image max-100x140 %}
          </div>
          {% endfor %}
        </div>
        <div class="col-lg-5 ml-n5 mt-2">
          <img
            class="border"
            style="width: 100%;"
            src="https://cdn.shopify.com/s/files/1/0070/8299/9875/products/10_89936ea2-4df2-4f3f-8e3d-7e923e7c21bd_grande.jpg?v=1542444325"
          />
        </div>
        <div class="col-lg-5 border-bottom">
          <p>
            {{ page.title }}
          </p>
          <span class="fa fa-star checked"></span>
          <span class="fa fa-star checked"></span>
          <span class="fa fa-star checked"></span>
          <span class="fa fa-star"></span>
          <span class="fa fa-star"></span>
          <p>
            {{ page.Price }}
          </p>
          <p>
            {{ page.Description }}
          </p>
          <div>
          <form action="{% url "cart:add" page.id %}"
          method="post"
          class="form-inline">

{% csrf_token %}
            <div>
              <label>Quantity</label>
              <input type="number" name='quantity' value='1' step="1" min="1" />
            </div>
            <div class="mt-4 ">
              <input 
              type="submit"
              value="Add to cart"
              class="col-lg-5 btn btn-success ">   
              <input 
                    value="Add to WishList"
                    class="col-lg-5 btn btn-success "
                />
            </div>
            <div >
              <input
                class="col-lg-7 mt-2 btn btn-primary"
                type="submit"
                value="Buy It Now"
              />
            </div>
          </form>
        </div>
          {% with categories=page.Categories.all %}
      {% if categories %}
      
      <div class="mt-5" >
        <h6>Categories</h6>
        <ul>
            {% for category in categories %}
                <li style="display: inline">
                    <a href="{% routablepageurl product_index_page "post_by_category" category.slug %}">{{ category.name }}</a>
                </li>
            {% endfor %}
        </ul>
      </div>
    {% endif %}
{% endwith %}
        </div>
      </div>
    </div>
  </section>

  <!-- Section for Descrition Comments and Reviews-->
  <section class="mt-5">
    <div class="container">
      <div class="d-flex flex-row justify-content-center ">
        <button
          class="tab-switcher border-bottom btn  mr-2 btn-lg"
          data-tab-index="0"
          tabindex="0"
        >
          Descriptions
        </button>
        <button
          class="tab-switcher border-bottom btn  mr-2 btn-lg"
          data-tab-index="1"
          tabindex="0"
        >
          Comments
        </button>
        <button
          class="tab-switcher border-bottom btn  mr-2 btn-lg"
          data-tab-index="2"
          tabindex="0"
        >
          Reviews
        </button>
      </div>

      <div id="allTabsContainer" class="mt-5">
        <div class="tab-container " data-tab-index="0">
          <p>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dicta
            veniam provident id nisi quo esse ex porro tempore sequi perferendis
            officia quidem fuga, aspernatur optio? Recusandae, amet. Asperiores,
            vel suscipit.
          </p>
          <p>
            Features
          </p>
          <div>
            <span>
              Brand Name :
            </span>

            <span>
              No Name
            </span>
          </div>
          <div>
            <span>
              Sizes Available :
            </span>

            <span>
              S/ M/ L
            </span>
          </div>
          <div>
            <span>
              Addition Features :
            </span>
          </div>
        </div>
        <div class="tab-container" data-tab-index="1" style="display:none;">
          <ul class="list-unstyled">
            <li class="media">
              <img src="..." class="mr-3" alt="..." />
              <div class="media-body">
                <p class="mt-0 mb-1">Anamous</p>
                <p>
                  Cras sit amet nibh libero, in gravida nulla. Nulla vel metus
                  scelerisque ante sollicitudin.
                </p>
              </div>
            </li>
          </ul>
        </div>
        <div class="tab-container" data-tab-index="2" style="display:none;">
          <p>
            Revews
          </p>
        </div>
      </div>
    </div>
  </section>

  <!--
        Section for related products
    -->
  <section class="mt-5">
    <div class="container">
      <p class="relatedproducts border-bottom">
        Related Products
      </p>
      <div class="row">
        {% for product in products %}
        {% if page.Categories.all == product.categories.all and page.title != product.title  %}
        <div class="col-lg-3  ">
          <a href="{{ product.url }}">
            <div
              class="row no-gutters  align-self-center position-relative "
              style="background-color: white;"
            >

              <div class="col-auto align-self-center ">
                <img
                  class=" ml-3"
                  src="https://cdn.shopify.com/s/files/1/0070/8299/9875/products/15_4b8b7cc7-c445-4c11-8022-0652106d2f95_grande.jpg?v=1541587242"
                  width="200"
                  height="200"
                />
              </div>
              <div class="col d-flex flex-column ">
                <strong class=" align-self-center">{{ product.title }}</strong>
                <p class="mb-auto text-center">
                  {{ product.Description }}
                </p>
                <p>
                  {{ product.Categories.all }}
                </p>
              </div>
            </div>
          </a>
        </div>
        {% endif %}
        {% endfor %}
      </div>
    </div>
  </section>
{% endblock %}

Products/templates/Products/product_index_page.html
{% extends "base.html" %}

{% load static %}
{% load wagtailimages_tags  wagtailroutablepage_tags %}
{% block content %}
<div style="height:15rem; " class="flex-column-reverse">

</div>
<div style="background-color: #f2f2f2">
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img class="d-block w-100" src="{% static 'images/happy_new.png' %}" alt="First slide">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="{% static 'images/sales_day.jpg' %}" alt="Second slide">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="{% static 'images/shop.gif' %}" alt="Third slide">
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

<section style="background-color: #f2f2f2; color: #424242;" class="py-5">
  <div class="container" >
    <h3>
      Categories
    </h3>
  </div>
    <section>
        <div class="py-2 ">
                <div class="container  " >
                  <div class="row ">
                      {% for category in categories %}
                    <div class="col-10 col-sm-6 col-md-5 col-lg-4  mt-2 ">
                            <a href="{% routablepageurl page "post_by_category" category.slug %}">
                            <div class=" ml-5 ml-sm-0 no-gutters  overflow-hidden flex-lg-column mb-4  h-lg-250 position-relative " style="background-color: white; text-align: center;">
                              <div class=" p-4 d-flex flex-column ">
                                <strong class="align-self-center">{{ category.name }}</strong>
                                 <img class="mt-2 col-lg-4 col-md-6 col-sm-6 col-6 align-self-center  "
                        src="{% static 'images/swigly_line.png' %}" alt="...">
                                 <strong class="mt-2  text-center">{{ category.Caterogy_Description }}</strong>
                              </div>
                              <div class=" align-self-center col-lg-10 col-md-9 col-sm-6 col-10 pl-5  img-responsive mb-2">
                               {% image category.image  original %}
                                 </div>
                            </div>
                            </a>
                          </div>
                          {% endfor %}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </section>
            <!-- section for New Arrivals High Rates -->
            <section>

            
            <section style="background-color: white;" class="pt-5">
              <div class="container">
                <div class="d-flex flex-row justify-content-center ">
                    <button  class="tab-switcher btn btn-primary mr-2 btn-lg" data-tab-index="0" tabindex="0">New Arrivals</button>
                    <button  class="tab-switcher btn btn-primary  mr-2 btn-lg" data-tab-index="1" tabindex="0" >Top Featured</button>
                    <button   class="tab-switcher btn btn-primary mr-2 btn-lg" data-tab-index="2" tabindex="0" >High Rated</button>
                  </div>
                <div id="allTabsContainer" class="mt-5">
                    <div class="tab-container" data-tab-index="0">
                        <div class="row">
                          {% for product in products %}
                            <div class="  col-lg-3 col-md-3 col-sm-4 col-6 mb-5" >
                                    <a  href="{{ product.url }}">
                                    <div class="   align-self-center position-relative " style="background-color: white;">
                                        <div class="align-self-center single-item">
                                              {% for item in product.gallery_images.all %}
                                              <div class="align-self-center  single-item   img-responsive">
                                                <div>
                                                {% image item.image original %}
                                                </div>
                                            </div>
                                            {% endfor %}
                                           </div>
                                      <div class=" mt-4 d-flex flex-column">
                                        <strong class=" align-self-center" style="color: #757575;">{{ product.title }}</strong>
                                         <p class="mb-auto text-center">{{ product.Description }}</p>
                                         <strong class="mb-auto text-center" > Price: Rs{{ product.Price }}</strong>
                                      </div>                                    
                                    </div>
                                    </a>
                                         </div>
                                         {% endfor %}
                              </div>
                    </div>
                    <!-- Tab container 1 for Top Featured-->
                    <div class="tab-container" data-tab-index="1" style="display:none;">
                        <div class="row">
                          {% for product in products %}
                          {% if product.TopFeatured %}
                        <div class="  col-lg-3 col-md-3 col-sm-4 col-6  mb-5" >
                                    <a  href="{{ product.url }}">
                                    <div class="   align-self-center position-relative " style="background-color: white;">
                                        <div class="align-self-center single-item">
                                              {% for item in product.gallery_images.all %}
                                              <div class="align-self-center    img-responsive">
                                                {% image item.image original %}
                                            </div>
                                          {% endfor %}
                                         </div>
                                    <div class="col d-flex flex-column">
                                      <strong class=" align-self-center">{{ product.title }}</strong>
                                       <p class="mb-auto text-center">{{ product.Description }}</p>
                                       <strong class="mb-auto text-center" > Price: Rs{{ product.Price }}</strong>
                                    </div>                                    
                                  </div>
                                  </a>
                                       </div>
                                       {% endif %}
                                       {% endfor %}                                                                          
                    </div>
                    </div>
                    <!-- Tab container for 2 high rated-->
                    <div class="tab-container" data-tab-index="2" style="display:none;">
                        <div class="row">
                          {% for product in products %}
                         <div class="  col-lg-3 col-md-3 col-sm-4 col-6  mb-5" >
                                    <a  href="{{ product.url }}">
                                    <div class="   align-self-center position-relative " style="background-color: white;">
                                        <div class="align-self-center single-item">
                                              {% for item in product.gallery_images.all %}
                                              <div class="align-self-center img-responsive">
                                                {% image item.image original %}
                                            </div>
                                          {% endfor %}
                                         </div>
                                    <div class="col d-flex flex-column">
                                      <strong class=" align-self-center">{{ product.title }}</strong>
                                       <p class="mb-auto text-center">{{ product.Description }}</p>
                                       <strong class="mb-auto text-center" > Price: Rs{{ product.Price }}</strong>
                                    </div>                                    
                                  </div>
                                  </a>
                                       </div>
                                       {% endfor %}
                        </div>
                    </div>
                </div>
              </div>
            </section>
          </section>
          </section>
{% endblock %}

Products/templates/Products/product_list.html
{% extends "base.html" %}

{% load static %}
{% load wagtailimages_tags  wagtailroutablepage_tags %}
{% block content %}
<div style="height:15rem; " class="flex-column-reverse">

</div>
<div  style="background-color: #f2f2f2 ; height:3rem;" >
    <p class="container p-2" style="font-size: small; font-family: Arial, Helvetica, sans-serif;color:#68d0e2;">
        home/category
    </p>

</div>
    <div class=" container mt-3">    
  <div class="row ">
      <div>
           <div class= 'col-md-12 border' style="background-color: #f2f2f2 ;font-size: 15px;" >
                        <p class="border-bottom py-2">
                            Shop by Categories
                        </p>
                        {% for category in categories %}
                       <p>
                            <a href="{% routablepageurl page "post_by_category" category.slug %}">{{ category.name }}</a>
                        </p>
                    {% endfor %}
                    </div> 
      </div>
                 <div class="ml-2">
                     <div class="border">
                            <nav class="nav">
                                <a class="nav-link active" href="#">All</a>
                                <a class="nav-link" href="#">Male</a>
                                <a class="nav-link" href="#">Female</a>
                                <a class="nav-link " href="#" tabindex="-1" aria-disabled="true">Kids</a>
                            </nav>

                     </div>
        <div class="row mt-3 ">
            {% for product in products %}
            <div class="  col-lg-3 col-md-3 col-sm-4 col-6 mb-5" >
                                    <a  href="{{ product.url }}">
                                    <div class="   align-self-center position-relative " style="background-color: white;">
                                        <div class="align-self-center single-item">
                                              {% for item in product.gallery_images.all %}
                                              <div class="align-self-center single-item img-responsive">
                                                <div>
                                                {% image item.image original %}
                                                </div>
                                            </div>
                                            {% endfor %}
                                           </div>
                                      <div class=" mt-4 d-flex flex-column">
                                        <strong class=" align-self-center" style="color: #757575;">{{ product.title }}</strong>
                                         <p class="mb-auto text-center">{{ product.Description }}</p>
                                         <strong class="mb-auto text-center" > Price: Rs{{ product.Price }}</strong>
                                      </div>                                    
                                    </div>
                                    </a>
                                         </div>
            {% endfor %}
        </div>
        </div>
        </div>
</div>
    {% endblock %}